### ISSUE TITLE
Integrate vm-bhyve with cloud-init

### ISSUE THREAD

**Issue by mateuszkwiatkowski** [churchers/vm-bhyve#289]
Hello @churchers!

Our internal tooling supports cloud-init and we'd like to move that into vm-bhvye so that other users may make use of it.
What's needed in the backstage:
1. in dedicated directory (may be temporary), generate two files. Examples:

meta-data:
```
instance-id: iid-local01
local-hostname: gitlab-runner-1.dev
```

user-data:
```
#cloud-config
chpasswd:
  list: |
    ubuntu:password
  expire: False

ssh_authorized_keys:
  - ssh-rsa examplePublicKey example@public.key
```
2. Generate iso file with these files:
`genisoimage  -output /zroot/vm/gitlab-runner-1.dev/seed.iso -volid cidata -joliet -rock user-data meta-data`
3. Mount this iso in the guest and boot:
```
disk1_type="ahci-cd"
disk1_name="seed.iso"
disk1_dev="file"
```

Cloud-init should detect the volume and pickup metadata from it.

Here's my idea for CLI interface for this feature:
1. Store for SSH public keys
It would work in similar way like store for iso or img files. Example:
```
$ vm ssh_pub_key add my-key "$(cat ~/.ssh/id_rsa.pub)"
$ vm ssh_pub_key
NAME        TYPE          FINGERPRINT
my-key      RSA           SHA256:PXUsDtDdmil28hcDApe97mg3xdhcrY0H5/Qwidk4AzE
```

2. Choose public key when creating VM:
```
$ vm create -t freebsd -c 4 -m 2048 -i xenial-server-cloudimg-amd64-uefi1.img -s 50G -k my-key gitlab-runner-1.dev
$ vm start gitlab-runner-1.dev
$ ssh ubuntu@gitlab-runner-1.dev
Welcome to Ubuntu 16.04.5 LTS (GNU/Linux 4.4.0-141-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

  Get cloud support with Ubuntu Advantage Cloud Guest:
    http://www.ubuntu.com/business/services/cloud

0 packages can be updated.
0 updates are security updates.


Last login: Wed Jan  9 23:41:59 2019 from 10.0.0.1
ubuntu@gitlab-runner-1:~$
```

That's it! Machine is ready to use. If you like the idea I'll come up with pull request.

**Comment by quexpl** [comment]
The `mkisofs` could be used too, for generating the iso file.
```
mkisofs -o ../seed.iso -V cidata -J -r user-data meta-data 
```

**Comment by brd** [comment]
No need to install `mkisofs`, `bsdtar` can create ISOs as well.

**Comment by churchers** [comment]
Really cool idea. Not looked into anything like cloud-init previously but being able to boot an image and ssh in immediately is pretty nifty.

I would probably call the sub-command something a bit shorter like `vm ssh-keys` and may be worth accepting the `.pub` filename directly which is a bit more user friendly than a call to `cat` in the command line,

**Comment by mateuszkwiatkowski** [comment]
To inject static network configuration `network-config` file should be added to seed.iso. Example:
```
version: 2
ethernets:
  interface0:
     match:
         macaddress: "58:9c:fc:00:d4:c2"
     set-name: eth0
     addresses:
     - 1.2.3.4/24
     gateway4: 1.2.3.1
     nameservers:
       addresses: [1.1.1.1]
```

For more information: https://cloudinit.readthedocs.io/en/latest/topics/network-config-format-v2.html
