### ISSUE TITLE
FreeBSD cloud-init not working with vtnet0

### ISSUE THREAD

**Issue by ivomarino** [churchers/vm-bhyve#556]
I'm currently creating a FreeBSD 14.1 VM using the following options:
```
vm create -t uefi -s 16G -c 2 -m 512M -i freebsd-14.0-zfs-2024-05-06.qcow2 -C \
   -n "ip=192.168.140.169/24;gateway=192.168.140.1;nameservers=192.168.140.1" \
   -k ~/.ssh/id_rsa.pub zfs-test-01
```

this creates the following network-config as defined by the [code](https://github.com/churchers/vm-bhyve/blob/master/lib/vm-core#L287-L298):

```
cat network-config
version: 2
ethernets:
  id0:
    set-name: eth0
    match:
      macaddress: "58:9c:fc:08:10:0e"
    addresses:
      - 192.168.140.169/24
    gateway4: 192.168.140.1
    nameservers:
      search: []
      addresses: [192.168.140.1]
```

the problem is my network interface is `vtnet0` and not `eth0`, this is what I get from the logs:
```
2024-08-17 12:12:43,216 - stages.py[DEBUG]: applying net config names for {'version': 2, 'ethernets': {'id0': {'set-name': 'eth
0', 'match': {'macaddress': '58:9c:fc:08:10:0e'}, 'addresses': ['192.168.140.169/24'], 'gateway4': '192.168.140.1', 'nameserver
s': {'search': [], 'addresses': ['192.168.140.1']}}}}
```

any ideas how this can be fixed? It works fine with Debian based VM images, thanks for inputs
